@api = http://localhost:5010

### At first, create an account
POST {{api}}/sign-up
Content-Type: application/json

{
  "email": "scenario-user1@domain.com",
  "password": "secret",
  "role": "user"
}

### Authenticate and grab the access token
# @name sign_in
POST {{api}}/sign-in
Content-Type: application/json

{
  "email": "scenario-user1@domain.com",
  "password": "secret"
}

### Get your user account details
@accessToken = {{sign_in.response.body.$.accessToken}}
GET {{api}}/me
Authorization: Bearer {{accessToken}}

